import SwiftUI
import MapKit
struct ContentView:View { @StateObject var store=PinStore(); @StateObject var lm=LocationManager(); var body:some View{TabView{Home(store:store,lm:lm).tabItem{Label("Home",systemImage:"house.fill")}; MapScreen(pins:store.pins).tabItem{Label("Map",systemImage:"map.fill")}; Create(store:store,lm:lm).tabItem{Label("Create Pin",systemImage:"plus.circle.fill")}; Pins(store:store).tabItem{Label("My Pins",systemImage:"mappin.and.ellipse")}; Profile().tabItem{Label("Profile",systemImage:"person.fill")}}.tint(.green)} }
struct Home:View{@ObservedObject var store:PinStore;@ObservedObject var lm:LocationManager;var body:some View{NavigationStack{ScrollView{VStack(alignment:.leading,spacing:18){Text("NaijaPin").font(.largeTitle.bold());Text("Stop explaining. Just share your Pin.").foregroundStyle(.secondary);HStack{Label(lm.location == nil ? "Location not captured":"GPS location captured",systemImage:"location.fill");Spacer();Button("Locate"){lm.request()}.buttonStyle(.borderedProminent)}.padding().background(.green.opacity(0.1),in:RoundedRectangle(cornerRadius:18));Text("Your Pins").font(.title2.bold());ForEach(store.pins.prefix(3)){PinCard(pin:$0)}}.padding()}.navigationTitle("Home")}}}
struct Create:View{@ObservedObject var store:PinStore;@ObservedObject var lm:LocationManager;@State var name="",address="",road="",landmark="",gate="",directions="";var body:some View{NavigationStack{Form{Section("Pin details"){TextField("Pin name",text:$name);TextField("Address",text:$address);TextField("Main road",text:$road);TextField("Landmark",text:$landmark);TextField("Gate / entrance",text:$gate);TextField("Extra directions",text:$directions,axis:.vertical)};Section("GPS"){Text(lm.location == nil ? "No GPS location captured":"GPS location ready");Button("Use My Current Location"){lm.request()}};Button("Save Pin"){guard let l=lm.location else{return};store.add(Pin(name:name.isEmpty ? "My Place":name,address:address,mainRoad:road,landmark:landmark,gate:gate,directions:directions,latitude:l.coordinate.latitude,longitude:l.coordinate.longitude));name="";address="";road="";landmark="";gate="";directions=""}.disabled(lm.location == nil || name.isEmpty)}.navigationTitle("Create a Pin")}}}
struct MapScreen:View{let pins:[Pin];@State var pos:MapCameraPosition=.automatic;var body:some View{NavigationStack{Map(position:$pos){ForEach(pins){Marker($0.name,coordinate:$0.coordinate)}}.navigationTitle("Map")}}}
struct Pins:View{@ObservedObject var store:PinStore;var body:some View{NavigationStack{List{ForEach(store.pins){p in NavigationLink(p.name){Detail(pin:p)}}.onDelete(perform:store.delete)}.navigationTitle("My Pins")}}}
struct Detail:View{let pin:Pin;var body:some View{Form{Text(pin.address.isEmpty ? "No address":pin.address);Text(pin.mainRoad.isEmpty ? "No main road":pin.mainRoad);Text(pin.landmark.isEmpty ? "No landmark":pin.landmark);Text(pin.gate.isEmpty ? "No gate description":pin.gate);Text(pin.directions.isEmpty ? "No extra directions":pin.directions);Button("Open in Apple Maps"){UIApplication.shared.open(URL(string:"http://maps.apple.com/?ll=\(pin.latitude),\(pin.longitude)")!)}}.navigationTitle(pin.name)}}
struct PinCard:View{let pin:Pin;var body:some View{VStack(alignment:.leading){Label(pin.name,systemImage:"mappin.circle.fill").font(.headline);if !pin.address.isEmpty{Text(pin.address).font(.subheadline)};if !pin.landmark.isEmpty{Text("Landmark: \(pin.landmark)").font(.caption).foregroundStyle(.secondary)}}.padding().frame(maxWidth:.infinity,alignment:.leading).background(.gray.opacity(0.08),in:RoundedRectangle(cornerRadius:14))}}
struct Profile:View{var body:some View{NavigationStack{Form{Section("NaijaPin"){Text("Digital Nigerian addresses built around GPS, landmarks, roads and entrance directions.")};Section("Privacy"){Text("This starter stores pins locally on the device. A production release should add secure accounts, cloud sharing, privacy controls and a backend.").font(.footnote)}}.navigationTitle("Profile")}}}
